apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"6","meta.helm.sh/release-name":"ollama","meta.helm.sh/release-namespace":"ollama"},"creationTimestamp":"2025-02-01T07:41:36Z","generation":10,"labels":{"app.kubernetes.io/instance":"ollama","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ollama","app.kubernetes.io/version":"0.5.7","helm.sh/chart":"ollama-1.4.0"},"name":"ollama","namespace":"ollama","resourceVersion":"82205646","uid":"6b3dca70-cfe5-4e3a-8b37-fa72034ec768"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/instance":"ollama","app.kubernetes.io/name":"ollama"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"ollama","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"ollama","app.kubernetes.io/version":"0.5.7","helm.sh/chart":"ollama-1.4.0"}},"spec":{"containers":[{"env":[{"name":"OLLAMA_NUM_THREADS","value":"8"}],"image":"ollama/ollama:0.5.7","imagePullPolicy":"IfNotPresent","lifecycle":{"postStart":{"exec":{"command":["/bin/sh","-c","while ! /bin/ollama ps \u003e /dev/null 2\u003e\u00261; do\n  sleep 5\ndone\necho \"deepseek-r1:latest\" | xargs -n1 /bin/ollama pull\necho \"mxbai-embed-large\" | xargs -n1 /bin/ollama pull\n/bin/sh /scripts/post-start.sh\n"]}}},"livenessProbe":{"failureThreshold":6,"httpGet":{"path":"/","port":"http","scheme":"HTTP"},"initialDelaySeconds":120,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"name":"ollama","ports":[{"containerPort":11434,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":6,"httpGet":{"path":"/","port":"http","scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":3},"resources":{"limits":{"cpu":"16","memory":"16Gi"},"requests":{"cpu":"16","memory":"16Gi"}},"securityContext":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/root/.ollama","name":"ollama-data"},{"mountPath":"/scripts","name":"script-volume"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"ollama","serviceAccountName":"ollama","terminationGracePeriodSeconds":30,"volumes":[{"name":"ollama-data","persistentVolumeClaim":{"claimName":"ollama"}},{"configMap":{"name":"scripts-config-map"},"name":"script-volume"}]}}}}
    meta.helm.sh/release-name: ollama
    meta.helm.sh/release-namespace: ollama
  creationTimestamp: "2025-02-01T07:41:36Z"
  generation: 10
  labels:
    app.kubernetes.io/instance: ollama
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ollama
    app.kubernetes.io/version: 0.5.7
    helm.sh/chart: ollama-1.4.0
  name: ollama
  namespace: ollama
  resourceVersion: "82205646"
  uid: 6b3dca70-cfe5-4e3a-8b37-fa72034ec768
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: ollama
      app.kubernetes.io/name: ollama
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ollama
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ollama
        app.kubernetes.io/version: 0.5.7
        helm.sh/chart: ollama-1.4.0
    spec:
      containers:
      - env:
        - name: OLLAMA_NUM_THREADS
          value: "16"
        image: ollama/ollama:0.5.7
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  while ! /bin/ollama ps > /dev/null 2>&1; do
                    sleep 5
                  done
                  echo "deepseek-r1:latest" | xargs -n1 /bin/ollama pull
                  echo "mxbai-embed-large" | xargs -n1 /bin/ollama pull
                  /bin/sh /scripts/post-start.sh
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: ollama
        ports:
        - containerPort: 11434
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "16"
            memory: 16Gi
          requests:
            cpu: "16"
            memory: 16Gi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-data
        - name: script-volume
          mountPath: /scripts
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ollama
      serviceAccountName: ollama
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ollama-data
        persistentVolumeClaim:
          claimName: ollama
      - name: script-volume
        configMap:
          name: scripts-config-map